server.port=8085

fsa.api.base-url=https://marketplaces-dev.fsa.gov.ru/mrktpls/api/v1


fsa.api.key=mp_AaCvf1C3cFmsMw9LDkbxRg.LSxDkX7M8nyL3d80CVGJtQ


fsa.client.timeout=30000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
